//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTC.CvsntGitImporter.TestCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CvsLogParserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CvsLogParserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTC.CvsntGitImporter.TestCode.Properties.CvsLogParserResources", typeof(CvsLogParserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCS file: /cvs/xjtag/dev/src/Project/test/BuiltInLDDTypesTest.cs,v
        ///Working file: BuiltInLDDTypesTest.cs
        ///head: 1.3
        ///branch:
        ///locks: strict
        ///access list:
        ///symbolic names:
        ///	branch2: 1.1.0.4
        ///	branch1: 1.1.0.2
        ///keyword substitution: kv
        ///total revisions: 8;	selected revisions: 8
        ///description:
        ///----------------------------
        ///revision 1.3
        ///date: 2009/09/17 14:13:27;  author: johnb;  state: Exp;  lines: +0 -0;  kopt: kv;  commitid: 6d84ab244054630;  filename: BuiltInLDDTypesTest.cs;
        ///Commit #3
        ///------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCS file: /cvs/xjtag/dev/src/Project/test/File.cs,v
        ///Working file: File.cs
        ///head: 1.2
        ///branch:
        ///locks: strict
        ///access list:
        ///symbolic names:
        ///	branch1: 1.1.0.2
        ///keyword substitution: kv
        ///total revisions: 3;	selected revisions: 3
        ///description:
        ///----------------------------
        ///revision 1.2
        ///date: 2013/05/09 11:03:30;  author: john;  state: Exp;  lines: +50 -0;  kopt: kv;  commitid: 2220518b828121b1;  mergepoint: 1.1.2.1;  filename: File.cs;
        ///3.0: Add File.
        ///----------------------------
        ///revision 1.1
        ///date: 2013 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileAddedOnBranch {
            get {
                return ResourceManager.GetString("FileAddedOnBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCS file: /cvs/xjtag/dev/src/Project/test/BuiltInLDDTypesTest.cs,v
        ///Working file: BuiltInLDDTypesTest.cs
        ///head: 1.3
        ///branch:
        ///locks: strict
        ///access list:
        ///symbolic names:
        ///	some-branch: 1.1.0.2
        ///keyword substitution: kv
        ///total revisions: 8;	selected revisions: 8
        ///description:
        ///----------------------------
        ///revision 1.3
        ///date: 2009/09/17 14:13:27;  author: johnb;  state: Exp;  lines: +0 -0;  kopt: kv;  commitid: 6d84ab244054630;  filename: BuiltInLDDTypesTest.cs;
        ///Commit #3
        ///----------------------------
        ///rev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mergepoint {
            get {
                return ResourceManager.GetString("Mergepoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///RCS file: /cvs/xjtag/dev/src/Project/test/.cvsignore,v
        ///Working file: .cvsignore
        ///head: 1.2
        ///branch:
        ///locks: strict
        ///access list:
        ///symbolic names:
        ///keyword substitution: kv
        ///total revisions: 2;	selected revisions: 2
        ///description:
        ///----------------------------
        ///revision 1.2
        ///date: 2009/03/04 11:54:43;  author: johnb;  state: Exp;  lines: +2 -1;  kopt: kv;  filename: .cvsignore;  bugid: 4564;
        /// (bug 4564)
        ///----------------------------
        ///revision 1.1
        ///date: 2009/02/03 12:25:27;  author: konstantina;  state: E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MissingCommitId {
            get {
                return ResourceManager.GetString("MissingCommitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///RCS file: /cvs/project/demo©.xje,v
        ///head: 1.3
        ///branch:
        ///locks: strict
        ///access list:
        ///symbolic names:
        ///keyword substitution: kv
        ///total revisions: 4;	selected revisions: 4
        ///description:
        ///----------------------------
        ///revision 1.3
        ///date: 2010/06/25 16:50:02;  author: john;  state: dead;  lines: +0 -0;  kopt: kv;  commitid: d584c24de370163;  filename: demo©.xje;  bugid: 5488;
        ///Blah blah
        ///----------------------------
        ///revision 1.2
        ///date: 2009/06/02 16:33:33;  author: john;  state: Exp;  lines: +359 -0;  kopt:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonAscii {
            get {
                return ResourceManager.GetString("NonAscii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///RCS file: /cvs/xjtag/dev/src/Project/test/.cvsignore,v
        ///Working file: .cvsignore
        ///head: 1.2
        ///branch:
        ///locks: strict
        ///access list:
        ///symbolic names:
        ///keyword substitution: kv
        ///total revisions: 2;	selected revisions: 2
        ///description:
        ///----------------------------
        ///revision 1.2
        ///date: 2009/03/04 11:54:43;  author: johnb;  state: Exp;  lines: +2 -1;  kopt: kv;  commitid: c0449ae6c023bd1;  filename: .cvsignore;  bugid: 4564;
        /// (bug 4564)
        ///----------------------------
        ///revision 1.1
        ///date: 2009/02/03 12:25:27;  au [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StandardFormat {
            get {
                return ResourceManager.GetString("StandardFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///RCS file: /cvs/xjtag/dev/src/Project/test/.cvsignore,v
        ///Working file: .cvsignore
        ///head: 1.2
        ///branch:
        ///locks: strict
        ///access list:
        ///symbolic names:
        ///keyword substitution: kv
        ///total revisions: 2;	selected revisions: 2
        ///description:
        ///----------------------------
        ///revision 1.2
        ///date: 2009/03/04 11:54:43;  author: johnb;  state: dead;  lines: +2 -1;  kopt: kv;  commitid: c0449ae6c023bd1;  filename: .cvsignore;  bugid: 4564;
        /// (bug 4564)
        ///----------------------------
        ///revision 1.1
        ///date: 2009/02/03 12:25:27;  a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StateDead {
            get {
                return ResourceManager.GetString("StateDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///RCS file: /cvs/xjtag/dev/src/Project/test/.cvsignore,v
        ///Working file: .cvsignore
        ///head: 1.2
        ///branch:
        ///locks: strict
        ///access list:
        ///symbolic names:
        ///	tag2: 1.2
        ///	tag1: 1.1
        ///keyword substitution: kv
        ///total revisions: 2;	selected revisions: 2
        ///description:
        ///----------------------------
        ///revision 1.2
        ///date: 2009/03/04 11:54:43;  author: johnb;  state: Exp;  lines: +2 -1;  kopt: kv;  commitid: c0449ae6c023bd1;  filename: .cvsignore;  bugid: 4564;
        /// (bug 4564)
        ///----------------------------
        ///revision 1.1
        ///date:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
    }
}
